name: Executar Testes Unitários

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Caso tenha um requirements.txt

    - name: Rodar testes unitários
      run: |
        python -m unittest discover -s . -p "test_*.py"
